language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --no-interaction --dev --prefer-dist
  - ./vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/ ./

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  # Upload coverage data to Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
